spring.application.name=budgetprocess

spring.datasource.url=jdbc:postgresql://tst-tankeraidb-1a.c03k26sm6tu4.us-east-1.rds.amazonaws.com:5432/familyspencesdb?currentSchema=familyspences
spring.datasource.username=family_user
spring.datasource.password=S0ftw4re3#$
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgres

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=300000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.dynamic=true

budget.procesar.exchange-name=x.budget.exchange

budget.procesar.routing-key-income-create=income.create
budget.procesar.routing-key-income-update=income.update
budget.procesar.routing-key-income-delete=income.delete
budget.procesar.queue-income-create=budget.income.create.queue
budget.procesar.queue-income-update=budget.income.update.queue
budget.procesar.queue-income-delete=budget.income.delete.queue
